name: Java
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - run: ./gradlew check --no-daemon --stacktrace
